// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbsaxhigypnuedehejuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNic2F4aGlneXBudWVkZWhlanV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzIwODQsImV4cCI6MjA2OTMwODA4NH0.8R1gMoJFPv-MH1lDgFNcLSDKQYAiqxD9hwZUXOFH6nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safe localStorage access
const getStorageAdapter = () => {
  try {
    // Check if localStorage is available
    if (typeof window !== 'undefined' && window.localStorage) {
      return localStorage;
    }
  } catch (error) {
    console.warn('localStorage not available, using fallback storage');
  }

  // Fallback storage for environments where localStorage isn't available
  return {
    getItem: () => null,
    setItem: () => {},
    removeItem: () => {},
  };
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorageAdapter(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
