name: Deploy para Locaweb via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: fizko1
          server: ftp.fizko.com.br
          port: 22
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: './*'
          remote_path: '/home/fizko1/public_html/'
          sftp_only: true
